name: flutter_virtu_muse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  shared_preferences: ^2.1.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  shake_animation_widget: ^3.0.4
  animate_do: ^4.2.0
  flip_card: ^0.7.0
  flutter_staggered_grid_view: ^0.7.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/tabbar/
    - assets/images/humans/
    - assets/images/themes/
    - assets/images/spin/
    - assets/images/badge/

  fonts:
    - family: Lato
      fonts: 
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Thin.ttf
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
          style: italic